# Generated by Django 3.1.1 on 2021-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='display_resolution',
            field=models.CharField(default=251506, max_length=255, verbose_name='Display resolution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_refresh_rate',
            field=models.CharField(default=251506, max_length=255, verbose_name='Screen refresh rate'),
            preserve_default=False,
        ),
    ]
