# Generated by Django 3.1.1 on 2021-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210505_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='video',
        ),
        migrations.AddField(
            model_name='notebook',
            name='battery_capacity',
            field=models.CharField(default=251506, max_length=255, verbose_name='Battery capacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='dimensions',
            field=models.CharField(default=251506, max_length=255, verbose_name='Dimensions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='max_ram_memory',
            field=models.CharField(default=251506, max_length=255, verbose_name='Possibility of RAM expansion to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='operating_system',
            field=models.CharField(default=251506, max_length=255, verbose_name='Operating system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='processor_model',
            field=models.CharField(default=251526, max_length=255, verbose_name='Model processor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_type',
            field=models.CharField(default=251506, max_length=255, verbose_name='Memory RAM type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='rom',
            field=models.CharField(default=251506, max_length=255, verbose_name='Built-in memory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_card',
            field=models.CharField(default=251506, max_length=255, verbose_name='Video card model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_card_memory',
            field=models.CharField(default=251506, max_length=255, verbose_name='Video card memory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='weight',
            field=models.CharField(default=251506, max_length=255, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Memory RAM'),
        ),
    ]
